### ISSUE TITLE
[BUG for developers] Docker file gives error

### ISSUE THREAD

**Issue by YahyaFazlani** [Tech-With-Tim/twtcodejam.net#28]
**Describe Your issue**

**Steps To Reproduce**
Steps to reproduce the bug:
1.  Clone the repo
2.  Run `docker build .`

**Screenshots**

**Browser Info**
 - accessed on Desktop
 - OS: Windows (WSL)

**What were you trying to do**
Run the app using docker

**Additional context**
The docker file causes an error: `failed to compute cache key: "/public" not found: not found`

**Comment by Shubhaankar-sharma** [comment]
hey @YahyaFazlani we are not setting docker up on this repo it was the initial idea but since deployment was already done and a rewrite is coming there was no point...and there are many things that are not correctly setup in this repo that is causing issues in dockerizing this repo...

**Comment by YahyaFazlani** [comment]
Ok, I didn't know that. But if you would not like docker then why not just delete the dockerfile since it may give people the wrong idea.

**Comment by Shubhaankar-sharma** [comment]
Ok thanks
