### ISSUE TITLE
Our secrets module

### ISSUE THREAD

**Issue by pranavbaburaj** [Tech-With-Tim/twtcodejam.net#33]
What is the `our_secrets` module in the `settings.py`

I cannot run the project without it :smile:

**Comment by SnowballSH** [comment]
1. Please view [Contributing guideline](https://github.com/Tech-With-Tim/twtcodejam.net/blob/master/CONTRIBUTE.md)
2. `our_secrets.py` is where you store your database key and password, information, etc. Please see [example](https://github.com/Tech-With-Tim/twtcodejam.net/blob/master/our_secrets.example.py) for the file (you need to make it)

**Comment by SnowballSH** [comment]
Also, if you want to contribute to the future version, please see [rewrite](https://github.com/Tech-With-Tim/Frontend), thanks!
